config/routes.rb
Rails.application.routes.draw do
  root 'gossips#index'
  get 'sessions/new'
  get '/contact', to: 'static_pages#contact'
  get '/team', to: 'static_pages#team'
  get '/index', to: "static_pages#index"
  get 'message/:user_entry', to: 'message#show'

  resources :gossips, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :users, only: [:new, :create, :index, :show, :edit, :update]
  resources :cities, only: [:new, :create, :index, :show, :edit, :update]
  resources :comments, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :sessions
  
  
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  
  belongs_to :city
  has_many :gossips
  has_many :likes
  has_many :comments, as: :comment_type
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
  #def index
    #@gossips = Gossip.all
  #end


  def index
    @users = User.all

  end

  def new
    
    # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
  end

  def create
     city = City.find_by(name: params[:city])
    @user = User.new(
      'email' => params[:email],
      'password' => params[:password],
      'first_name' => params[:first_name],
      'last_name' => params[:last_name],
      'describtion' => params[:describtion],
      'age' => params[:age],
      'city' => city
    )
      puts "%" * 60
      puts @user.city
      puts @user.age
      puts @user.first_name
      puts @user.last_name
      puts @user.email
      puts @user.describtion
      puts @user.password
      puts city
      puts "%" * 60
    if @user.save
      redirect_to gossips_path
    else 
      render "new"
    end
   
  end

  def show
    @user = User.find(params[:id])
    # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
  end

  def edit
    # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
  end

  def update
    # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params
    # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
  end

  def destroy
    # Méthode qui récupère le potin concerné et le détruit en base
    # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
  end
end

app/views/users/index.html.erb
    <%= @users.each do |user| %>
      
        <p>
        <a href="<%= user_path(user.id) %>" class="btn btn-primary">
        <%= user.first_name %>
        <%= user.last_name %>
        </a>
        </p>
      
    <% end %>

app/views/users/new.html.erb
<center>
<form action= <%= users_path %> method="POST">
<input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %> >
  <label for="fname">Prénom</label>
  <input type="text" id="first_name" name="first_name"><br><br>
  <label for="lname">Nom de famille</label>
  <input type="text" id="last_name" name="last_name"><br><br>
  <label for="lname">Description</label>
  <input type="text" id="describtion" name="describtion"><br><br>
  <label for="lname">Age</label>
  <input type="text" id="age" name="age"><br><br>
  <label for="lname">Ville ( mettez Bahringerfurt svp sinon ca marche pas lol )</label>
  <input type="text" id="city" name="city"><br><br>
  <label for="lname">Email</label>
  <input type="text" id="email" name="email"><br><br>
  <label for="lname">Mot de passe</label>
  <input type="password" id="password" name="password"><br><br>
  <input type="submit" value="Submit">
</form>
</center>

app/views/users/show.html.erb
<center>

<br />

<h4><u> Informations sur l'auteur </u></h4>

<br />

<p> Nom de famille : <%= @user.last_name %> </p>

<p> Prénom : <%= @user.first_name %> </p>

<p> Description : <%= @user.describtion %> </p>

<p> E-mail : <%=@user.email%></p>

<p> Age : <%= @user.age %> </p>

<p> Ville : <%= @user.city.name %>
<%= link_to " page de la ville ", city_path, class: "btn btn-primary" %> </p>

</center>