config/routes.rb
Rails.application.routes.draw do
  root 'gossips#index'
  get 'sessions/new'
  get '/contact', to: 'static_pages#contact'
  get '/team', to: 'static_pages#team'
  get '/index', to: "static_pages#index"
  get 'message/:user_entry', to: 'message#show'

  resources :gossips, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :users, only: [:new, :create, :index, :show, :edit, :update]
  resources :cities, only: [:new, :create, :index, :show, :edit, :update]
  resources :comments, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :sessions
  
  
end

app/models/gossip.rb
class Gossip < ApplicationRecord
 validates :title,
        presence: true,
        length: { minimum: 3, maximum: 14 }
    validates :content,
        presence: true

    belongs_to :user
    belongs_to :tag, optional: true
    has_many :likes
    has_many :comments, as: :comment_type
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController 
  #def index
    #@gossips = Gossip.all
  #end



  def index
    @gossips = Gossip.all
    @comments = comments_all
    
  end

  def new
    # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
  end

  def create
    #Récupération des champs du formulaire
    @post = Gossip.new(
      'title' => params[:title],
      'content' => params[:content],
      'user_id' => session[:user_id],
      'tag_id' => Tag.all.sample.id
    )
    if @post.save
      redirect_to gossips_path
    else 
      render "new"
    end
  
  end

  def show
    @gossip = Gossip.find(params[:id])
    puts "$" * 60
    puts @id = params[:id]
    puts "$" * 60
    
    # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    gossip_params = params.require(:gossip).permit(:title, :content)
    @gossip.update(gossip_params)
    redirect_to gossips_path
    

  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to gossips_path
  end

  private

  def gossip_params
    params.require(:gossip).permit(:title, :content)
  end

  def gossip_find
    Gossip.find(params[:id])
  end

  def comments_all
    Comment.all
  end
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/views/gossips/edit.html.erb
<center>
<h1> Editer le gossip </h1>

<%= form_for @gossip do |f| %>
  <div class="form-group">
    <label>Titre du gossip</label>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label>Contenu du gossip</label>
    <%= f.text_area :content, class: 'form-control' %>
  </div>
  <div class="form-group">
  <button type="submit">modifier le gossip</button>
  </div>
<% end %>
</center>

app/views/gossips/index.html.erb
<style>
.jumbotron-fluid1 {  
        display: flex ;
        padding:10px;
      background-color: #EC8A28;
      margin:10px auto;
      border-radius:10px;
      color:#333;
      width: 1200px;
      height: 160px;
      justify-content : center ;    
	}
    .jumbotron-fluid2  {  
        display: flex ;
        padding:10px;
      background-color: #EC8A28;
      margin:10px auto;
      border-radius:10px;
      color:#333;
      width: 1200px;
      height: 2000px;      
	}
</style>

<div class="container">
    <div class="jumbotron jumbotron-fluid1" style="background-color: #aaa">
        <form class="form-inline justify-content-center">
            <div class="container">
                <h1 class="display-12"> Bienvenue sur The Gossip Project ! </h1>
                <hr class="my-8"> 
                <center><%= link_to "Ajoute ton gossip à la base de données", new_gossip_path, class: "btn btn-success" %></center>  
            </div> 
        </form>
    </div>    
</div>
  
<div class="container">
    <div class="jumbotron jumbotron-fluid2" style="background-color: #aaa">
        <div class="container">
            <h1><u><center> Banque des gossips </center></u></h1>
            <br>
            <% @gossips.each do |gossip| %>
            <p>
            <a href="<%= gossip_path(gossip.id) %>" class="btn btn-primary">description</a>
            <a href="<%= edit_gossip_path(gossip.id) %>" class="btn btn-warning">editer</a>
            <a href="<%= gossip_path(gossip.id) %>" class="btn btn-danger" data-confirm="etes vous sur?" data-method="DELETE" >supprimer</a>
            <strong>Titre</strong> : <%= gossip.title %>, <strong>Contenu</strong> : <%= gossip.content %>
            </p>
            <hr class="my-8">
            <% end %>
        </div>
    </div>
</div>
    



    
    

app/views/gossips/new.html.erb
<center>
<form action= <%= gossips_path %> method="POST">
<input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %> >
  <label for="fname">Title</label>
  <input type="text" id="title" name="title"><br><br>
  <label for="lname">Content</label>
  <input type="text" id="content" name="content"><br><br>
  <input type="submit" value="Submit">

</form>
</center>

app/views/gossips/show.html.erb
<center>
<br />
<h2><strong><u> Gossip °<%= @id %> </u></strong></h2>
<br />

<p><strong> Titre </strong>: <%= @gossip.title %> </p>

<p><strong> Contenu</strong> : <%= @gossip.content %> </p>

<p><strong> Auteur </strong>: <%= @gossip.user.first_name %> <%= @gossip.user.last_name %> 
<%= link_to " description auteur ", user_path, class: "btn btn-primary" %> </p>

<p><strong> Ville</strong> : <%= @gossip.user.city.name %> 
<%= link_to " page de la ville ", city_path, class: "btn btn-primary" %> </p>

<br />

<h3><u> Liste des Commentaires </u></h3>
  <p><% @gossip.comments.each do |comment| %>
    <strong>Commentaire</strong> :
    <%= comment.content %> 
    <br>
    <strong>Auteur</strong> :
    <%= User.find(@gossip.user.id).first_name %> 
    <%= User.find(@gossip.user.id).last_name %>
  </p>
  <% end %>

<%= link_to " créer un nouveau commentaire ", new_comment_path, class: "btn btn-success" %>
<br />
<br />
<a href ="<%= gossips_path %>" class="btn btn-primary">Revenir aux début</a>

</center>